# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy source files
COPY . ./

# Build the project
RUN npm run build

# Set NODE_ENV to production
ENV NODE_ENV=production

# Expose port if required (not specified, but usually not needed for MCP via stdio)

# Start the MCP server
CMD ["npm", "start"]