# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Install jq to modify package.json
RUN apk add --no-cache jq

# Create working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Remove the problematic dev dependency (@modelcontextprotocol/inspector) from package.json
RUN cat package.json | jq 'del(.devDependencies["@modelcontextprotocol/inspector"])' > package.tmp.json \
    && mv package.tmp.json package.json

# Install all dependencies (including dev deps needed for build)
RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Build the project (TypeScript to JavaScript)
RUN npm run build

# Expose necessary port if needed (MCP typically uses stdio, so no port exposed)

# Set the default command for the container
CMD ["node", "dist/index.js"]
