# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./

# Install dependencies without running prepare scripts (if any)
RUN npm install --ignore-scripts

# Copy source files
COPY . ./

# Build the project
RUN npm run build

# Expose port if required (not specified, but usually not needed for MCP via stdio)

# Set the default command
CMD ["npm", "start"]
